export const ServiceData = [
    {
        imgUrl: "assets/images/service-a.jpg",
        heading: "Home Cooked Food",
        subHeading: "Right at your home",
        description: "Why order food from Zomato when you can have a healthy home made meal cooked by our worker, right at your home and according to your preferences and customisations? ",
        listItem1: "Provide the worker with all the raw material and guidelines",
        listItem2: "Enjoy the healthy home cooked food along with your family",
        listItem3: "Pay the worker directly",
    },
    {
        imgUrl: "assets/images/service-b.jpg",
        heading: "Elder Citizen Care",
        subHeading: "At your doorstep",
        description: "WHY WORRY ABOUT LEAVING YOUR aged PARENTS ALONE AT HOME WHILE YOU GO TO WORK when we have our HouzKeepo to look after them? (everything in small letters)",
        listItem1: "Pick the highest rated",
        listItem2: "Pay the amount directly to the worker",
        listItem3: "Get trained workers to take care of your aged parents",
    },
    {
        imgUrl: "assets/images/service-c.jpg",
        heading: "Personal Baby Sitter",
        subHeading: "To take care of your baby while you’re away/busy",
        description: "Why worry about your little baby while we have our HouzKeepo trained to perfection to take proper care of your baby while you are away?",
        listItem1: "Get Trained Professionals to look after your baby while you’re away",
        listItem2: "Facilitated direct contact to the HouzKeepo in order to keep track of their where abouts",
        listItem3: "Pay them directly with no third person coming up in between",
    },
    {
        imgUrl: "https://cdn1.designhill.com/assets/dh/images/homepage-images/service/studio-tile.png?ver=2.12.37",
        heading: 'Designhill Studio',
        subHeading: 'Stunning visuals made easy!',
        description: 'Studio by Designhill is an intelligent & user-friendly design tool for everyone—a quick-fix for pro-designer and an ultimate web-based',
        listItem1: 'World-class library of customizable & ready-to-use templates',
        listItem2: 'A handy tool for everyone—pro-designers as well as novices',
        listItem3: 'All-in-one design solution with a unique experience',
    },
    {
        imgUrl: "https://cdn1.designhill.com/assets/dh/images/homepage-images/service/custom-tile.png?ver=2.12.37",
        heading: 'Custom Clothing',
        subHeading: 'Personalized clothing for every occasion!',
        description: 'Get trendy custom clothing designs to flaunt your unique style! It’s an ocean of custom products oozing with holiday spirit and more. Brand',
        listItem1: 'A touch of artistry, you may not find elsewhere',
        listItem2: 'A momentous gift for loved ones',
        listItem3: 'A perfect destination for promotional items',
    }
]